name: MemoSample-CI
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - '**.yaml'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - '**.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # JDKのセットアップ
      - name:  set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # gradleコマンドに実行権限を付与
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 依存関係の出力
      - name: Displays the Android dependencies of the project
        run: ./gradlew androidDependencies

      # コンパイル
      - name: Run Compile
        run: ./gradlew assembleDebug